name: Build

on: push

jobs:

  x86:
    name: x86
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind
      - name: Build
        run: |
          cd src && make EMBED=menu.ipxe && make bin-x86_64-efi/ipxe.efi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: x86 Binaries
          path: |
            src/bin/*.rom
            src/bin/*.mrom
            src/bin/ipxe.dsk
            src/bin-x86_64-efi/ipxe.efi
            src/bin/ipxe.iso
            src/bin/ipxe.lkrn
            src/bin/ipxe.pxe
            src/bin/ipxe.usb
