name: Build

on: push

jobs:

  x86:
    name: x86
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind
      - name: Build
        run: |
          cd src && make EMBED=menu.ipxe
      - name: Export Artifact
        run: |
          cd src/bin
          pwd
          ls -la
