name: Build

on: push

jobs:

  x86:
    name: x86
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind
      - name: Build (BIOS)
        run: |
          make -j 4 -C src EMBED=menu.ipxe
      - name: Build (Everything)
        run: |
          make -j 4 -C src everything EMBED=menu.ipxe
      - name: Test
        run: |
          valgrind ./src/bin-i386-linux/tests.linux
          valgrind ./src/bin-x86_64-linux/tests.linux
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: x86 Binaries
          path: |
            ./src/bin-i386-efi/*
            !./src/bin-i386-efi/**/*
            ./src/bin-x86_64-efi/*
            !./src/bin-x86_64-efi/**/*
            ./src/bin-x86_64-pcbios/*
            !./src/bin-x86_64-pcbios/**/*
            ./src/bin/*
            !./src/bin/**/*
            !./src/**/.gitignore
            !./src/**/*.a
            !./src/**/*.defs
            !./src/**/*.deps
            !./src/**/*.ids
            !./src/**/*.list
            !./src/**/*.map
            !./src/**/*.o
            !./src/**/*.tmp
            !./src/**/*.zinfo


  arm32:
    name: ARM32
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux gcc-arm-none-eabi
      - name: Build
        run: |
          make -j 4 -C src CROSS=arm-none-eabi- \
               bin-arm32-efi/intel.efi EMBED=menu.ipxe \
               bin-arm32-efi/intel.usb EMBED=menu.ipxe \
               bin-arm32-efi/intel.iso EMBED=menu.ipxe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ARM32 Binaries
          path: |
            ./src/bin-arm32-efi/*
            !./src/bin-arm32-efi/**/*
            !./src/**/*.a
            !./src/**/*.deps
            !./src/**/*.ids
            !./src/**/*.list
            !./src/**/*.map
            !./src/**/*.o
            !./src/**/*.tmp

  arm64:
    name: ARM64
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux gcc-aarch64-linux-gnu
      - name: Build
        run: |
          make -j 4 -C src CROSS=aarch64-linux-gnu- \
               bin-arm64-efi/ipxe.efi EMBED=menu.ipxe \
               bin-arm64-efi/ipxe.usb EMBED=menu.ipxe \
               bin-arm64-efi/ipxe.iso EMBED=menu.ipxe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ARM64 Binaries
          path: |
            ./src/bin-arm64-efi/*
            !./src/bin-arm64-efi/**/*
            !./src/**/*.a
            !./src/**/*.deps
            !./src/**/*.ids
            !./src/**/*.list
            !./src/**/*.map
            !./src/**/*.o
            !./src/**/*.tmp
