name: Build

on: push

jobs:

  x86:
    name: x86
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind
      - name: Build ipxe.dsk
        run: |
          cd src && make bin/ipxe.dsk EMBED=menu.ipxe
      - name: Build ipxe.efi
        run: |
          cd src && make bin-x86_64-efi/ipxe.efi EMBED=menu.ipxe
      - name: Build ipxe.iso
        run: |
          cd src && make bin/ipxe.iso EMBED=menu.ipxe
      - name: Build ipxe.lkrn
        run: |
          cd src && make bin/ipxe.lkrn EMBED=menu.ipxe
      - name: Build ipxe.pxe
        run: |
          cd src && make bin/ipxe.pxe EMBED=menu.ipxe
      - name: Build ipxe.usb
        run: |
          cd src && make bin/ipxe.usb EMBED=menu.ipxe
      - name: Merge Artifacts
        run: |
          mkdir -p  ~/artifacts
          cp src/bin/ipxe.dsk ~/artifacts/.
          cp src/bin-x86_64-efi/ipxe.efi ~/artifacts/.
          cp src/bin/ipxe.iso ~/artifacts/.
          cp src/bin/ipxe.lkrn ~/artifacts/.
          cp src/bin/ipxe.pxe ~/artifacts/.
          cp src/bin/ipxe.usb ~/artifacts/.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: x86 Binaries
          path:  ~/artifacts/*
